[package]
name = "arg-parse"
version = "0.1.0"
edition = "2021"
authors = ["Mahesh Vangala <vangalamaheshh@gmail.com>"]
license = "Apache 2.0 + MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
