[package]
name = "web_socket_app"
version = "0.1.0"
authors = ["Mahesh Vangala <vangalamaheshh@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix = "0.10.0"
actix-web-actors = "3.0.0"
